### ISSUE TITLE
Mining Tab has nothing on right side of screen

### ISSUE THREAD

**Issue by thorman123** [FluffierThanThou/ColonyManager#122] opened 2018-09-03 21:12 UTC
there is the new job part on the left and the options in the middle but on the right there is nothing there. it has no manage option or any way to choose which ores to mine...
![colony manager photo](https://user-images.githubusercontent.com/21047353/45001587-df86b200-af93-11e8-9c2c-b9a6b6a1158f.jpg)
[output_log.txt](https://github.com/FluffierThanThou/ColonyManager/files/2346547/output_log.txt)
[Mod List XML.zip](https://github.com/FluffierThanThou/ColonyManager/files/2346552/Mod.List.XML.zip)

**Comment by FluffierThanThou** [comment] 2018-09-05 08:33
Ok, should be fixed. 

I should note that this is caused by a rock that is classified as a _resourceRock_ but has no _mineableThing_. This is not normally possible and means some other mod is creating buggy rock/mineral types.

**Closed** 2018-10-14 08:51 UTC
Labels: todo
